name: bild
on: [ push, workflow_dispatch ]
jobs:
  build_name:
    runs-on: ubuntu-latest
    steps:
      - name: get kode
        uses: actions/checkout@v3
      - name: instal debs
        run: npm ci
      - name: build proekt
        run: npm run build
      - name: artifakt
        uses: actions/upload-artifact@v3
        with:
          path: build
          name: build_file
  deploy:
    needs: build_name
    runs-on: ubuntu-latest
    steps:
      - name: get build proekt
        uses: actions/download-artifact@v3
        with:
          name: build_file