name: razvertivanie deploy
on: push
jobs:
  vipolnaem_rabotu:
    runs-on: ubuntu-latest
    steps:
      - name: poluchit` repositoriy kode
        uses: actions/checkout@v3
      - name: ustanovka zavisimosti
        run: npm ci
      - name: run test
        run: npm run test
  proverka coda lint:
    runs-on: ubuntu-latest
    steps:
      - name: poluchit` repositoriy kode
        uses: actions/checkout@v3
      - name: ustanovka zavisimosti
        run: npm ci
      - name: run lint
        run: npm run lint
  sozdanie koda bild:
    runs-on: ubuntu-latest
    steps:
      - name: poluchit` repositoriy kode
        uses: actions/checkout@v3
      - name: ustanovka zavisimosti
        run: npm ci
      - name: run build
        run: npm run build
      - name: rabota deploq idet
        run: echo rabota idet...