name: everen
on:
  workflow_dispatch:
  push:
env:
  NOD_EV: production
  GS_N: ${{ secrets.GSEKRET }}
jobs:
  erve:
    runs-on: ubuntu-latest
    steps:
      - name: print env bild
        run: |
          echo "${{ env.NOD_EV }}"
          echo "${{ env.GS_N }}"
  deploy:
    runs-on: ubuntu-latest
    env:
      NOD_EV: dva tri dva
    steps:
      - name: print env deploy
        run: |
          echo "${{ env.NOD_EV }}"
          echo "${{ env.GS_N }}"